### ISSUE TITLE
Study class does not produce a workspace when OUTPUT_PATH is not specified. 

### ISSUE THREAD

**Issue by robinson96** [LLNL/maestrowf#155] opened 2018-10-25 20:22 UTC
when using maestro as a library, I instantiated a `Study` object with the study environment, parameters, and steps, but no output path. The object says the default is `./`, but a workspace was not created when calling `study.create_workspace()`. 
It's exactly the process followed in maestro.py, but without the extra logic for parsing / adding $(SPECROOT), and $(OUTPUT_PATH). 

``` 
git describe 
v1.1.3-1-gfd990ce
```

**Comment by jsemler** [comment] 2019-03-13 02:13
I am unable to reproduce this with version 1.1.4dev1.2 calling `study.setup_workspace()` which generates the `out_path` directory. I couldn't find `create_workspace` in the `Study` class.

@FrankD412 -- I did notice if `None` is passed to the `out_path` it overrides the default `cwd` and causes an error `AttributeError: 'NoneType' object has no attribute 'endswith'`.  Should `None` also default to the `cwd`?

**Comment by FrankD412** [comment] 2019-05-10 21:02
@jsemler -- is that specifically when using the `Study` class in a library capacity? It runs just fine through Maestro when the `OUTPUT_PATH` is not specified.

**Comment by FrankD412** [comment] 2019-07-14 20:20
I'm closing this issue -- I've not seen it reproduced.

**Closed by FrankD412** 2019-07-14 20:20 UTC
Labels: bug, help wanted
