### ISSUE TITLE
Unnable to detect "END JOB" signal of IBM Spectrum LSF workload manager

### ISSUE THREAD

**Issue by landajuela** [LLNL/maestrowf#195] opened 2019-09-04 00:06 UTC
Branch: interfaces/adapter/lsf

Problem: Maestro is not able to detect the ending signal of a batch job under the IBM Spectrum LSF workload manager.

More details: The job is labeled as "PENDING" whereas the "bjobs" command of LSF gives the job as "FINISHED".

**Comment by FrankD412** [comment] 2019-09-06 06:04
After debugging with @landajuela, the issue turned out to be that Maestro's LSF status call to `bjobs` included the `-q` option to filter on the queue. Lassen currently has a priority workaround that takes the normal queue and moves it based on the priority the user has at the time. Because Maestro assumes that the queue name is going to be the same as the one requested at submission, all jobs scheduled get filtered out and their status never updated.

I've just checked in a change that should fix it, but a longer terms solution on what to do if this happens should be determined.

**Comment by FrankD412** [comment] 2019-09-10 23:00
@landajuela and I talked, and he confirmed that the bug was fixed

**Closed by FrankD412** 2019-09-10 23:00 UTC
Labels: Bugfix, Confirmed, bug
