### ISSUE TITLE
slurm job names

### ISSUE THREAD

**Issue by doutriaux1** [LLNL/maestrowf#213] opened 2020-01-06 21:18 UTC
When scheduling a job with slurm e.g:

```yaml
description:
  name: ibm_postprocess
  description: Does all post processing after we run shocktube

batch:
  type:  slurm
  queue: pbatch
  host:  surface
  bank:  cbronze

study:
  - name: hdf5
    description: Generates hdf5 files from MashExtract
    run:
      cmd: |
         binary_2_hdf5.py -r $(RUN) -m "{'node': None}" --root=$(IBM_PATH)/base
      depends: []
      nodes: 1
      procs: 1
      walltime: "24:00:00"
      depends: []
```

In the directory the `hdf5` step I get:

```
-rwx------ 1 cdoutrix cdoutrix 339 Jan  6 13:09 hdf5_RUN.molar.0.0_shock.1.1_taper.0.9_skew.0.9.slurm.sh
-rw------- 1 cdoutrix cdoutrix   0 Jan  6 13:09 slurm-374670.out
```

It would be nice to get the job name output to match the `.sh` file.

I believe the slurm option is:

```
#SBATCH --job-name="[name here]"
```

**Comment by FrankD412** [comment] 2020-01-06 22:17
So, I know that the job name is substituted [here](https://github.com/LLNL/maestrowf/blob/develop/maestrowf/interfaces/script/slurmscriptadapter.py#L109), but for safety we substitute in underscores. That should match the script name. Do you have example output that shows the `SBATCH` job name header not being used?

**Comment by doutriaux1** [comment] 2020-01-06 22:24
@FrankD412 I'm assuming the yaml posted at top of this issue and as you can see the output log is called `slurm-374670.out`

Do you need anything else? I believe you can put `ls` for the command it should be the same.

**Comment by FrankD412** [comment] 2020-01-06 22:29
Do you happen to have the header to the script that YAML spec generated? I'm interest to see if the job name is set there (it should be). I'm mentally going towards the name being used for the log name, but I feel like I'm conflating SLURM with LSF.

I'm vaguely remembering a `%J` or something to that effect with a `-o` flag in the SLURM header, which I'm not seeing in Maestro's code -- having what was explicitly generated will let me verify again SLURM documentation.

**Comment by doutriaux1** [comment] 2020-01-06 22:59
@FrankD412 is that what you need:

```
#!/bin/bash
#SBATCH -N 1
#SBATCH -p pbatch
#SBATCH -A cbronze
#SBATCH -t 24:00:00
#SBATCH -J hdf5_RUN.molar.0.7_shock.1.1_taper.0.9_skew.0.9
#SBATCH --comment "Generates hdf5 files from MashExtract"

 binary_2_hdf5.py -r molar.0.7_shock.1.1_taper.0.9_skew.0.9 -m "{'node': None}" --root=/p/lscratchh/cdoutrix/cdoutrix/IBM/workaround/base
```

**Comment by FrankD412** [comment] 2020-01-07 14:52
Alright, after some googling it looks like this is a separate flag. According to SLURM's [documentation](https://slurm.schedmd.com/sbatch.html) you can add the following to the header:

```
-e, --error=<filename pattern>
Instruct Slurm to connect the batch script's standard error directly to the file name specified in the "filename pattern". By default both standard output and standard error are directed to the same file. For job arrays, the default file name is "slurm-%A_%a.out", "%A" is replaced by the job ID and "%a" with the array index. For other jobs, the default file name is "slurm-%j.out", where the "%j" is replaced by the job ID. See the filename pattern section below for filename specification options.
```

Marking this as confirmed.

**Comment by FrankD412** [comment] 2020-01-22 13:45
@doutriaux1 -- please take a look at #220; I've made a small fix to the SLURM adapter to produce the desired logs. In my testing, the scripts are formatted just fine and produce the desired output.

**Closed** 2020-01-22 18:32 UTC
Labels: Confirmed, Good First Issue, bug
